'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Increments

    '''<summary>
    '''lblNormalIncrementDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormalIncrementDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''normalIncrement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents normalIncrement As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSickIncrementsDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSickIncrementsDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sickIncrements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sickIncrements As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SDSIncrementNormalLeaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDSIncrementNormalLeaves As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SDSIncrementSickLeaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDSIncrementSickLeaves As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SDSIncrementDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDSIncrementDate As Global.System.Web.UI.WebControls.SqlDataSource
End Class
